import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import styles from '../styles/Home.module.scss';
//component
import Button from '../components/btn';
import Slider from '../components/slider';
//lib
import { motion } from 'framer-motion';

type test = {
  img: string;
  title: string;
};

//スライダー画像urlとalt（componentsに渡す）
const SliderData: { img: string; title: string }[] = [
  { img: 'https://placekitten.com/1920/800', title: 'slider1' },
  { img: 'https://placekitten.com/g/1920/800', title: 'slider2' },
];
const test = ['https://placekitten.com/1920/800'];
const Home: NextPage = () => {
  const DynamicComponent = dynamic(() => import('../components/switching-theme'));

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ ease: 'easeInOut', duration: 1 }}
    >
      <Slider data={SliderData}></Slider>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>About Page</h1>
          <Link href={`/`} scroll={false}>
            <a className={styles.link}>Index Link</a>
          </Link>
          <p className={styles.description}>
            <DynamicComponent />
          </p>
          <Button text={'ボタンコンポーネントテスト'}></Button>
        </main>

        <footer className={styles.footer}>
          <a
            href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            target='_blank'
            rel='noopener noreferrer'
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </motion.div>
  );
};

export default Home;
