import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.scss';
import dynamic from 'next/dynamic';
//lib
import { motion } from 'framer-motion';
//componets
import Header from '../components/header';
import Footer from '../components/footer';

const Home: NextPage = () => {
  const DynamicComponent = dynamic(() => import('../components/switching-theme'));
  return (
    <>
      <Header></Header>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ ease: 'easeInOut', duration: 1 }}
      >
        <div className={styles.container}>
          {/* <DynamicComponent /> */}
          <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          <main className={styles.main}>
            <h1 className={styles.title}>Dark mode test</h1>
            <Link href={`/about/`} scroll={false}>
              <a className={styles.link}>About Link</a>
            </Link>
            {/* <p className={styles.description}>
          Please here
        </p> */}
            <p className={styles.description}>
              <DynamicComponent />
            </p>

            <div className={styles.grid}>
              <a href='https://nextjs.org/docs' className={styles.card}>
                <h2>Card components</h2>
                <p>ダークモードのテスト dark mode!</p>
              </a>

              <a href='https://nextjs.org/learn' className={styles.card}>
                <h2>Card components</h2>
                <p>ダークモードのテスト dark mode!</p>
              </a>
            </div>
          </main>
        </div>
      </motion.div>
      <Footer></Footer>
    </>
  );
};

export default Home;
